### ISSUE TITLE
Problem to build omegaOsg on Ubuntu

### ISSUE THREAD

**Issue by ntoand** [uic-evl/omegalib#185]
I try a fresh build on Ubuntu 16.04 using ./omega get  master cyclops and get following errors:

[  2%] Built target omicron
[ 55%] Built target FreeImage
[ 61%] Built target freetype
[ 66%] Built target ftgl
[ 67%] Built target glew
[ 80%] Built target omega
[ 84%] Built target omegaToolkit
[ 85%] Built target GLFW
[ 86%] Built target displaySystem_GLFW
[ 87%] Built target bullet
[ 88%] Built target osg
[ 89%] Built target osgWorks
[ 91%] Built target osgBullet
[ 91%] Building CXX object modules/omegaOsg/src/CMakeFiles/omegaOsg.dir/OsgModule.cpp.o
In file included from /home/toand/git/omegalib/master/modules/omegaOsg/./omegaOsg/OsgModule.h:39: ,
                 from /home/toand/git/omegalib/master/modules/omegaOsg/src/OsgModule.cpp:36:
/home/toand/git/omegalib/master/modules/omegaOsg/./omegaOsg/OsgRenderPass.h:112:13: error: ‘Stat’ was not declared in this scope
         Ref<Stat> myTriangleCountStat;
             ^
/home/toand/git/omegalib/master/modules/omegaOsg/./omegaOsg/OsgRenderPass.h:112:17: error: template argument 1 is invalid
         Ref<Stat> myTriangleCountStat;
                 ^
/home/toand/git/omegalib/master/modules/omegaOsg/./omegaOsg/OsgRenderPass.h:113:13: error: ‘Stat’ was not declared in this scope
         Ref<Stat> myCullTimeStat;
             ^
/home/toand/git/omegalib/master/modules/omegaOsg/./omegaOsg/OsgRenderPass.h:113:17: error: template argument 1 is invalid
         Ref<Stat> myCullTimeStat;
                 ^
/home/toand/git/omegalib/master/modules/omegaOsg/./omegaOsg/OsgRenderPass.h:114:13: error: ‘Stat’ was not declared in this scope
         Ref<Stat> myDrawTimeStat;
             ^
/home/toand/git/omegalib/master/modules/omegaOsg/./omegaOsg/OsgRenderPass.h:114:17: error: template argument 1 is invalid
         Ref<Stat> myDrawTimeStat;
                 ^
modules/omegaOsg/src/CMakeFiles/omegaOsg.dir/build.make:86: recipe for target 'modules/omegaOsg/src/CMakeFiles/omegaOsg.dir/OsgModule.cpp.o' failed
make[2]: *** [modules/omegaOsg/src/CMakeFiles/omegaOsg.dir/OsgModule.cpp.o] Error 1
CMakeFiles/Makefile2:790: recipe for target 'modules/omegaOsg/src/CMakeFiles/omegaOsg.dir/all' failed
make[1]: *** [modules/omegaOsg/src/CMakeFiles/omegaOsg.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by febret** [comment]
thanks for the report, I will test a build this evening.

**Comment by febret** [comment]
The error has been fixed. please do
``
> omega update master
> omega build master
``
(sub master with release if you are building the release branch)

**Comment by ntoand** [comment]
I cannot see the update in master. Did you push it?
